run:
	cd /Volumes/git/github/2025/gedcom-parse && ./testgedcom gedcom-parse-0.90.0/t/input/allged.ged

all:
	echo "We don't need Docker. This works on Mac OS."
	cd /Volumes/git/github/2025/gedcom-parse && make init && make && make test && ./testgedcom gedcom-parse-0.90.0/t/input/allged.ged
	@echo "TODO: get this working: ~/sarnobat.git/2023/genealogy/rohidekar.ged"
	@echo "'/Users/sarnobat/github/2025/gedcom-parse/gedcom-parse-0.90.0/gedcom flex bison lex yacc here.2025-02-13.txt'"
	
	