build:
	cp 
	cd /tmp/ \
		&& tar -xvf gedcom-parse-0.90.0.tar.gz \
		&& cd gedcom-parse-0.90.0/ \
		find
get:		
	wget 'https://master.dl.sourceforge.net/project/gedcom-parse/gedcom-parse/0.90.0/gedcom-parse-0.90.0.tar.gz?viasf=1'
	echo "TODO 2025-10 get the old C library build working"