# common logic
MYVALUE=world

# by default, make builds the first target
all:	clear	external
	echo "Building" $(MYVALUE)

external:
	cp /Users/sarnobat/computers.git/docker/.zshrc .

clear:
	echo "Cleared"
# 	rm .aliases

