FROM ubuntu:sridhar
COPY ccze /proj/
WORKDIR /proj/

RUN apt install -y autoconf
RUN apt install -y build-essential
RUN apt install -y gcc
RUN apt install -y libncurses5-dev
RUN apt install -y libpcre3-dev

RUN wget 'http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess'
RUN wget 'http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub'
RUN ./configure x86_64
RUN make
RUN make install

CMD ["echo", "Hello StackOverflow!"]
